testing_mode = true
payment_provider = "stripe" #bmac if using Buy Me A Coffee
stripe_api_key_test = "rk_test_51O0NQjJ97I3euEAUpN7ecPTvOJa7G7yv9qsmq8gRtsjQGTsiN0m9drIKIk7XUZf2Af4mWI6QGQljfLrBp4ZbpPPe00eGYlANCN" #only needed if using Stripe
stripe_api_key = "sk_live_..." #only needed if using Stripe
stripe_link = "https://buy.stripe.com/..." #only needed if using Stripe
stripe_link_test = "https://buy.stripe.com/test_bIYg32byH9Wk0Kc289" #only needed if using Stripe
client_id = "1029079214707-24r05noe2eijbbsjreir332grg9gp44o.apps.googleusercontent.com"
client_secret = "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"
redirect_url_test = 'http://localhost:8501/'
redirect_url = "https://my-saas-auca.streamlit.app"
bmac_api_key = "ey..." #only needed if using buy me a coffee
bmac_link = "https://www.buymeacoffee.com/..." #only needed if using buy me a coffee